### ISSUE TITLE
中文训练集问题

### ISSUE THREAD

**Issue by yyfanxing** [Sanster/tf_crnn#3]
作者您好,我用您提供的代码进行训练,但是测试效果好像不是很好(我统一生成8个字的文字图片,测试时8个字的识别率不高,识别少于8个字的图片没有一张能正确识别,crnn网络不是支持不定长的吗?).但我运行作者提供的模型,泛化能力非常好,而且准确率也很不错.不知道作者大概用了多少数据集进行训练?

**Comment by Sanster** [comment]
我用 [text_renderer](https://github.com/Sanster/text_renderer) 生成了 500W 的数据来训练，中文语料使用的是搜狗的新闻语料，英文用的是 wiki 的语料

**Comment by yyfanxing** [comment]
好的,非常感谢~,我再重新生成数据训练试试.

**Comment by mengzhibin** [comment]
@Sanster 不好意思，能否告知一下您生成这500w数据的yaml文件，是默认的设置嘛？里面设置项太多了，不太懂怎么调比较好
