### ISSUE TITLE
请问识别效果和效率与origin code 相比表现如何？

### ISSUE THREAD

**Issue by zzhanq** [Sanster/tf_crnn#5]
你好，非常感谢你的分享。不知道有没有与http://github.com/bgshih/crnn 原来的代码做比较，在准确率和效率上表现如何？

**Comment by Sanster** [comment]
这个要看训练集和测试集，网络结构都是一样的

**Comment by zzhanq** [comment]
恩，好的。那请问一下你的这个代码有没有一些评测，在你自己的测试集上准确率，效率如何？比如说按照你生成样本的代码随机生成一批数据测试

**Comment by Sanster** [comment]
网络的能力还是可以的，如果训练集和测试集都是生成的话，测试的准确率98是没问题的，但是要用到实际场景中，就看你的训练集和真实数据多相似了

**Comment by zzhanq** [comment]
好的，非常感谢，很棒的分享
